import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import ScrollToTopButton from "@/Components/ScrollToTopButton/ScrollToTopButton";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Serene Urgent Care And Mind Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Navbar />
        <main className="lg:min-h-[calc(100vh-491.7px)]">{children}</main>
        <Footer />

        <ScrollToTopButton />
      </body>
    </html>
  );
}
